### ISSUE TITLE
Migrate document into Metanorma format

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ogc-GeoPose#1]
@metanorma/editors could you please help encode this document (forked from https://github.com/opengeospatial/GeoPose) into the Metanorma format?

It will need the full suite of files (metanorma.yml, .github/ workflows).

This is requested from https://github.com/opengeospatial/ogc-metanorma-testing/issues/76

Thanks!

cc: @ghobona

**Comment by anermina** [comment]
@ronaldtse Can you please upload the original PDF for this document? I've been using the one available in the repo, but it doesn't completely match the text from already generated .adoc files.

**Comment by ronaldtse** [comment]
@anermina we are asked to directly convert the text from https://github.com/opengeospatial/GeoPose/tree/main/standard/standard to this repo, so there is no original PDF.

**Comment by anermina** [comment]
Thank you for confirmation @ronaldtse .

**Comment by ronaldtse** [comment]
Merged in #2.
