### ISSUE TITLE
Re-assign ModSpec identifiers according to OGC instructions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ogc-GeoPose#8]
This is a mapping provided by @ghobona:

[GeoPose.xlsx](https://github.com/metanorma/ogc-GeoPose/files/9714309/GeoPose.xlsx)

@metanorma/editors could you please help rename the identifiers as provided by this Excel sheet? Thanks!

**Comment by manuelfuenmayor** [comment]
Since there has been a re-configuration of the identifiers' name. It will be necessary to re-structure the `req/` folder according to the new names. Creating new files and re-locating old ones.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, should we take into account the "Sheet 2" of [GeoPose.xlsx](https://github.com/metanorma/ogc-GeoPose/files/9714309/GeoPose.xlsx)? It seems unfinished.

**Comment by manuelfuenmayor** [comment]
Maybe it is finished after all.
The re-structuring of `req/` folder is ready. I'm following with `conf/`.

**Comment by ghobona** [comment]
@manuelfuenmayor  I've just added Column D to Sheet 2.

So Column C (ConfClassID-New) shows the identifiers of conformance classes.

Column D (ConfTest) shows the identifiers of conformance tests.

Please have a look and let me know if you have any questions about the identifiers.

[GeoPose_2.xlsx](https://github.com/metanorma/ogc-GeoPose/files/9735755/GeoPose_2.xlsx)

**Comment by manuelfuenmayor** [comment]
Thanks @ghobona, now Sheet 2 is clearer.

I have two questions indeed:
1. In the last row of Column D, there are three comma-separated identifiers? Should I take these three into account or just the first one? (Original document only includes the first one.)
2. In Dependency column (Column K), the identifiers from row 56 onwards, don't match with any requirement entity:
  ![capture1](https://user-images.githubusercontent.com/33627611/194686851-8381b72d-29be-427b-8caa-a62db028724c.PNG)
 By association, I'm assuming that these correspond to conformance class IDs that need to be corrected with the new identifiers. Namely:
`/conf/basic_ypr_sdu` is `/conf/basic-ypr`
`/conf/basic_quaternion_sdu` is `/conf/basic-quaternion`
`/conf/advanced_sdu` is `/conf/advanced`... etc.
Am I right?

**Comment by manuelfuenmayor** [comment]
The re-structuring of `conf`/ folder is finished.
The correspondence issues that are left are due to authentic missing requirements in the document:
````
Requirements: (XML Line 001607): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001618): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001629): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001828): Requirement /req/graph/sdu-graph-transform-index has no corresponding Conformance test
Requirements: (XML Line 004371): Conformance test /conf/graph/sdu-graph-index has no corresponding Requirement
Requirements: (XML Line 004510): Conformance test /conf/chain/sdu-chain-index has no corresponding Requirement
Requirements: (XML Line 004995): Conformance class /conf/basic-ypr-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005039): Conformance class /conf/basic-quaternion-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005082): Conformance class /conf/basic-quaternion-encoding-json-strict has no corresponding Requirement class
Requirements: (XML Line 005124): Conformance class /conf/advanced-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005166): Conformance class /conf/chain-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005208): Conformance class /conf/graph-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005250): Conformance class /conf/series-regular-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005292): Conformance class /conf/series-irregular-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005334): Conformance class /conf/stream-encoding-json has no corresponding Requirement class
````
